name: next_vpn_lite
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  csv: ^5.0.2
  lottie: ^2.3.2
  flutter_internet_speed_test: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.14.0
  firebase_remote_config: ^4.2.3
  syncfusion_flutter_gauges:
  percent_indicator:
  fluttertoast:
  rflutter_alert:
  roundcheckbox: ^2.0.5
  avatar_glow: ^2.0.2
  flutter_screenutil: ^5.9.0
  flutter_zoom_drawer: ^3.1.1
  share_extend: ^2.0.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.2
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  dio: ^4.0.6
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  animated_text_kit:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  android: true
  ios: true
  color: 453984 # background color
  image: assets/images/eye_no_bg.png # path to your splash screen image
  image_background_color: Color(0xff453984), # background color behind the image

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eye_vpn_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
