// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCIoTcSzTb9swPlRdc8kPbMuVpriWJf0U',
    appId: '1:1057154829390:web:8c46a1e23424985853071f',
    messagingSenderId: '1057154829390',
    projectId: 'next-vpn-3e46a',
    authDomain: 'next-vpn-3e46a.firebaseapp.com',
    storageBucket: 'next-vpn-3e46a.appspot.com',
    measurementId: 'G-FHXXRYELL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WcMWouZo60PGUqndVdzBEJYQ_0iJPRk',
    appId: '1:1057154829390:android:c89029dc8a2a71b453071f',
    messagingSenderId: '1057154829390',
    projectId: 'next-vpn-3e46a',
    storageBucket: 'next-vpn-3e46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhdCoVzrgkaYBLWhjXmrpO5G7BnJuPfQ',
    appId: '1:1057154829390:ios:c274d07d5a2ae46853071f',
    messagingSenderId: '1057154829390',
    projectId: 'next-vpn-3e46a',
    storageBucket: 'next-vpn-3e46a.appspot.com',
    iosBundleId: 'com.app.eyevpnlite.eyeVpnLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhdCoVzrgkaYBLWhjXmrpO5G7BnJuPfQ',
    appId: '1:1057154829390:ios:7648b7d810e48c1953071f',
    messagingSenderId: '1057154829390',
    projectId: 'next-vpn-3e46a',
    storageBucket: 'next-vpn-3e46a.appspot.com',
    iosBundleId: 'com.app.eyevpnlite.eyeVpnLite.RunnerTests',
  );
}
